### ISSUE TITLE
Can't find variable: Highcharts - Only on iOS

### ISSUE THREAD

**Issue by veeramani-arthanari** [senthilnasa/high_chart#37]
Hello,
Thank you for your awesome library.

Recently I tried using it on one of my project. It's working fine on Android but in iOS I'm getting the below error

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 1, WKJavaScriptExceptionMessage: ReferenceError: Can't find variable: Highcharts, WKJavaScriptExceptionSourceURL: Unsupported Type: undefined, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 11}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1167:7)
web_kit_api_impls.dart:1167
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:479:28)
webkit_webview_controller.dart:479
<asynchronous suspension>
```

**Comment by senthilnasa** [comment]
Hi Veeramani,

Thank you for your kind words about the library! I appreciate your support.

The error you’re encountering suggests that the Highcharts scripts were not loaded successfully. This can happen if the scripts are not accessible or not loaded before the chart initialization. 

Could you please check and confirm the following?

### 1. Verify Script URLs
Ensure the scripts are added correctly to the `scripts` parameter in your `HighCharts` widget. For example:

```dart
HighCharts(
  loader: const SizedBox(
    child: LinearProgressIndicator(),
    width: 200,
  ),
  size: const Size(400, 400),
  data: _chartData,
  scripts: const [
    "https://code.highcharts.com/highcharts.js",
    "https://code.highcharts.com/modules/networkgraph.js",
    "https://code.highcharts.com/modules/exporting.js",
  ],
);
```

### 2. Check Internet Access
Confirm that the device running your application has a stable internet connection and can access the scripts hosted at the URLs. If there is restricted internet access, consider hosting the scripts locally or bundling them with your app.

### 3. Debugging the Issue
To debug further:
- Confirm that the `_chartData` being passed to the `HighCharts` widget is correctly formatted for Highcharts.
- If possible, log or print the errors to identify any additional issues during runtime.

If you still face the issue, please share the exact `_chartData` and the widget configuration you’re using so I can help further.

Thanks,  
**Senthil**
